---
- name: Check if secrets file exists in the role directory
  ansible.builtin.stat:
    path: "{{ secrets_file }}"
  register: role_secrets_stat
  delegate_to: localhost
  become: no

- name: Handle secrets generation if needed
  block:
    - name: Include secrets generation tasks
      ansible.builtin.include_tasks: generate-secrets.yaml
  when: not role_secrets_stat.stat.exists
  delegate_to: localhost
  become: no

- name: Include hub setup tasks
  ansible.builtin.import_tasks: hub.yaml
