---
# Only generate secrets if they are not already defined
- name: Generate secrets for Neon services
  ansible.builtin.set_fact:
    users: "{{ users | combine({item.key: {'password': lookup('password', '/dev/null chars=ascii_letters,digits length=32')}}) }}"
  loop: "{{ users | dict2items }}"
  no_log: true

- name: Generate secrets for HANA tokens
  ansible.builtin.set_fact:
    hana: "{{ hana | combine({item.key: lookup('password', '/dev/null chars=ascii_letters,digits length=64')}) }}"
  loop: "{{ hana | dict2items }}"
  no_log: true

- name: Combine all secrets into a single variable
  ansible.builtin.set_fact:
    neon_hub_secrets:
      users: "{{ users }}"
      hana: "{{ hana }}"
  no_log: true

- name: Save secrets to file
  copy:
    content: "{{ neon_hub_secrets | to_nice_yaml }}"
    dest: "{{ secrets_file }}"
  no_log: true
