---
- name: Install required packages
  apt:
    name: 
      - "{{ browser_package }}"
      - xorg
      - openbox  # Lightweight WM fallback
    state: present
    update_cache: yes

- name: Create kiosk user
  user:
    name: "{{ kiosk_user }}"
    create_home: yes
    shell: /bin/bash
    password: ""

- name: Ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'
  loop:
    - "/home/{{ kiosk_user }}/.config/autostart"
    - "/home/{{ kiosk_user }}/.config/plasma-workspace/env"
    - "/home/{{ kiosk_user }}/.config/openbox"

- name: Configure browser autostart
  template:
    src: templates/browser.desktop.j2
    dest: "/home/{{ kiosk_user }}/.config/autostart/browser.desktop"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'

- name: Check for display managers
  stat:
    path: "{{ item.path }}"
  register: dm_check
  loop:
    - { path: '/etc/gdm3', name: 'gdm' }
    - { path: '/etc/sddm.conf.d', name: 'sddm' }

- name: Configure GDM autologin
  copy:
    dest: /etc/gdm3/custom.conf
    content: |
      [daemon]
      AutomaticLoginEnable=true
      AutomaticLogin={{ kiosk_user }}
      WaylandEnable=true
      TimedLoginEnable=false
    mode: '0644'
  when: dm_check.results[0].stat.exists

- name: Ensure SDDM config directory exists
  file:
    path: /etc/sddm.conf.d
    state: directory
    mode: '0755'
  when: dm_check.results[1].stat.exists

- name: Configure SDDM autologin
  copy:
    dest: /etc/sddm.conf.d/autologin.conf
    content: |
      [Autologin]
      User={{ kiosk_user }}
      Session=plasma
      Relogin=true
    mode: '0644'
  when: dm_check.results[1].stat.exists

- name: Configure KDE startup script
  copy:
    dest: "/home/{{ kiosk_user }}/.config/plasma-workspace/env/kiosk.sh"
    content: |
      #!/bin/sh
      export KIOSK_URL="{{ webapp_url }}"
      # Disable screen locking
      kwriteconfig5 --file kscreenlockerrc --group Daemon --key Autolock false
      # Disable session restore
      kwriteconfig5 --file ksmserverrc --group General --key loginMode default
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'

- name: Configure Openbox autostart
  copy:
    dest: "/home/{{ kiosk_user }}/.config/openbox/autostart"
    content: |
      # Start browser in kiosk mode
      "{{ browser_package }}" --kiosk "{{ webapp_url }}" &
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'

- name: Configure automatic login (fallback)
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin {{ kiosk_user }} --noclear %I $TERM
      Type=idle
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Create README file with warning
  copy:
    dest: /home/neon/KIOSK-MODE-README.txt
    owner: "neon"
    group: "neon"
    mode: "0644"
    content: |
      IMPORTANT: This system is configured to run in dedicated kiosk mode.

      This means:
      - The machine will automatically start in kiosk mode on boot, as {{ kiosk_user }}
      - It will display the web interface at {{ webapp_url }}
      - Both GNOME and KDE Plasma are supported
      - A fallback to Openbox is configured if needed

      If you no longer want to run in kiosk mode, it can be removed by running
      the Neon AI Hub Installer script and indicating you do not want to install it.
      The script will remove the user and files it created.
