---
- name: Install browser
  apt:
    name: "{{ browser_package }}"
    state: present
    update_cache: yes

- name: Create kiosk user
  user:
    name: "{{ kiosk_user }}"
    create_home: yes
    shell: /bin/bash
    password: ""

- name: Ensure autostart directory exists
  file:
    path: "/home/{{ kiosk_user }}/.config/autostart"
    state: directory
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'

- name: Configure browser autostart
  template:
    src: templates/browser.desktop.j2
    dest: "/home/{{ kiosk_user }}/.config/autostart/browser.desktop"
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    mode: '0755'

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'

- name: Configure automatic login
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin {{ kiosk_user }} --noclear %I $TERM
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Create README file with warning
  copy:
    dest: /home/neon/KIOSK-MODE-README.txt
    owner: "neon"
    group: "neon"
    mode: "0644"
    content: |
      IMPORTANT: This system is configured to run in dedicated kiosk mode.

      This means:
      - The machine will automatically start in kiosk mode on boot, as {{ kiosk_user }}
      - It will display the web interface at {{ webapp_url }}

      If you no longer want to run in kiosk mode, it can be removed by running
      the Neon Hub Installer script and indicating you do not want to install it.
      The script will remove the user and files it created.
