---
- name: Copy Neon Node files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: neon
    group: neon
  loop:
    - {
        "src": "templates/neon-node/neon-node-requirements.j2.txt",
        "dest": "/home/neon/neon-node-requirements.txt",
      }
    - {
        "src": "templates/neon-node/start-node.py",
        "dest": "/home/neon/start-node.py",
      }
- name: Install Neon Node voice client
  ansible.builtin.pip:
    requirements: "/home/neon/neon-node-requirements.txt"
    virtualenv: "/home/neon/.venvs/neon-node"
    extra_args: "--pre" # TODO: Remove after a stable release
- name: Set up Neon Node services
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: neon
    group: neon
    mode: 0644
    backup: true
  loop:
    - {
        "src": "templates/neon-node/neon-node.service.j2",
        "dest": "/home/neon/.config/systemd/user/neon-node.service",
      }
- name: Enable and start Neon Node services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    force: true
    daemon_reload: true
    state: restarted
    linger: true
  loop:
    - neon-node.service
